removed chart validation

diff --git a/.github/workflows/common-pr-deployment-values-validation_old.yaml b/.github/workflows/common-pr-deployment-values-validation_old.yaml
--- a/.github/workflows/common-pr-deployment-values-validation_old.yaml
+++ b/.github/workflows/common-pr-deployment-values-validation_old.yaml
@@ -23,61 +23,61 @@ env:
   SCRIPTS_FOLDER: "./interop-infra-commons/scripts/helm"
 
 jobs:
-  # chart_validation:
-  #   name: Helm Chart validation
-  #   runs-on: ubuntu-22.04
-  #   strategy:
-  #     matrix:
-  #       chartType: ["microservice", "cronjob"]
-  #     fail-fast: false
-  #   steps:
-  #     - name: Checkout
-  #       id: checkout
-  #       uses: actions/checkout@v4
+  chart_validation:
+    name: Helm Chart validation
+    runs-on: ubuntu-22.04
+    strategy:
+      matrix:
+        chartType: ["microservice", "cronjob"]
+      fail-fast: false
+    steps:
+      - name: Checkout
+        id: checkout
+        uses: actions/checkout@v4
 
-  #     - name: Print inputs passed in
-  #       run: |
-  #         echo "Using infra_commons_tag: ${{ inputs.infra_commons_tag }}"
-  #         echo "Using strict_kube_linter_checks: ${{ inputs.strict_kube_linter_checks }}"
-  #         echo "Using environment: ${{ inputs.environment }}"
+      - name: Print inputs passed in
+        run: |
+          echo "Using infra_commons_tag: ${{ inputs.infra_commons_tag }}"
+          echo "Using strict_kube_linter_checks: ${{ inputs.strict_kube_linter_checks }}"
+          echo "Using environment: ${{ inputs.environment }}"
 
-  #     - name: Checkout scripts repository
-  #       uses: actions/checkout@v4
-  #       with:
-  #         repository: roberto-mondello-dgt/interop-infra-commons
-  #         path: interop-infra-commons
-  #         fetch-depth: 0
-  #         sparse-checkout: 'scripts/helm'
-  #         ref: ${{ inputs.infra_commons_tag }}
+      - name: Checkout scripts repository
+        uses: actions/checkout@v4
+        with:
+          repository: roberto-mondello-dgt/interop-infra-commons
+          path: interop-infra-commons
+          fetch-depth: 0
+          sparse-checkout: 'scripts/helm'
+          ref: ${{ inputs.infra_commons_tag }}
 
-  #     - name: Helm Chart Linting
-  #       id: helm_lint
-  #       env:
-  #         CHART_TYPE: ${{ matrix.chartType }}
-  #       run: |
-  #         set -euo pipefail
+      - name: Helm Chart Linting
+        id: helm_lint
+        env:
+          CHART_TYPE: ${{ matrix.chartType }}
+        run: |
+          set -euo pipefail
 
-  #         OPTIONS=""
+          OPTIONS=""
 
-  #         if [[ $CHART_TYPE == "microservice" ]]; then
-  #           OPTIONS=" --microservices "
-  #         elif [[ $CHART_TYPE == "cronjob" ]]; then
-  #           OPTIONS=" --jobs "
-  #         else
-  #           echo "Workflow cannot be run on selected chart $CHART_TYPE"
-  #           exit 1
-  #         fi
+          if [[ $CHART_TYPE == "microservice" ]]; then
+            OPTIONS=" --microservices "
+          elif [[ $CHART_TYPE == "cronjob" ]]; then
+            OPTIONS=" --jobs "
+          else
+            echo "Workflow cannot be run on selected chart $CHART_TYPE"
+            exit 1
+          fi
 
-  #         export PROJECT_DIR=$(pwd)
-  #         CHART_PATH="./commons/${{ inputs.environment }}/Chart.yaml"
+          export PROJECT_DIR=$(pwd)
+          CHART_PATH="./commons/${{ inputs.environment }}/Chart.yaml"
 
-  #         $SCRIPTS_FOLDER/helmLint-main.sh \
-  #         --debug \
-  #         --environment "${{ inputs.environment }}" \
-  #         --output console \
-  #         $OPTIONS \
-  #         --chart-path $CHART_PATH \
-  #         -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml
+          $SCRIPTS_FOLDER/helmLint-main.sh \
+          --debug \
+          --environment "${{ inputs.environment }}" \
+          --output console \
+          $OPTIONS \
+          --chart-path $CHART_PATH \
+          -i $PROJECT_DIR/commons/${{ inputs.environment }}/images.yaml
 
   microservices_validation:
     name: Microservices - Template & Lint
